const movies = [
  {
    title: 'Sonic',
    subtitle: 'The Movie',
    storyline: 'Sonic, the most famous blue hedgehog in the world, teams up with his friends to defeat the evil Doctor Eggman, a mad scientist who plans to take over the world, and Doctor Robotnik, responsible for imprisoning innocent animals in robots.',
    rating: 3.5,
    imagePath: 'https://uploads.jovemnerd.com.br/wp-content/uploads/2019/11/v-sonic-o-filme-poster.jpg',
  },
  {
    title: 'The Avengers',
    subtitle: 'End Game',
    storyline: 'After Thanos eliminates half of the living creatures, the Avengers must deal with the loss of friends and loved ones. With Tony Stark wandering lost in space without water and food, Steve Rogers and Natasha Romanov lead the resistance against the mad titan.',
    rating: 4.7,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt2AdqgHxcqjiTh1LtxqPoKBAGafjt5LhkLQ&usqp=CAU',
  },
  {
    title: 'The Croods',
    subtitle: 'The Croods',
    storyline: 'Prehistory family sees their cave destroyed. After that, the Croods set out on an adventure in search of a new place to live, led by a very imaginative boy who helps them to discover an entirely new world.',
    rating: 3.6,
    imagePath: 'https://i1.wp.com/2.bp.blogspot.com/-xUK3cIFIPFs/UL_MIMiYWKI/AAAAAAAAADk/ec-qT9rdNuM/s1600/The-Croods-A-Dreamworks-Movie.jpg?ssl=1',
  },
  {
    title: 'Justice League',
    subtitle: 'Justice League',
    storyline: 'Driven by the restoration of his faith in humanity and inspired by the selfless act of Superman, Bruce Wayne summons his new ally Diana Prince to battle against an even greater, newly awakened enemy. Together, Batman and Wonder Woman agilely seek out and recruit a team of meta-humans, but even with the unprecedented formation of the hero league, it could be too late to save the planet from a catastrophic onslaught.',
    rating: 2.0,
    imagePath: 'https://www.hollywoodreporter.com/wp-content/uploads/2017/10/dmbgznxx4aaysjv_-_p_2017.jpg?w=681&h=383&crop=1',
  },
  {
    title: 'Star Wars',
    subtitle: 'The Force Awakens',
    storyline: 'The fall of Darth Vader and the Empire led to the rise of a dark new force: the First Order. They look for the missing Jedi Luke Skywalker. The resistance desperately tries to find him first to save the galaxy.',
    rating: 4.6,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyEPmUPXdi-moZzwwN8VdvDyqyK0PfuNDY6g&usqp=CAU',
  },
  {
    title: 'Suicide Squad',
    subtitle: 'Hell to Pay',
    storyline: 'Amanda Waller forms a special squad full of imprisoned villains to retrieve a mystical object.',
    rating: 1.3,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaiKMwyaIpjnJ0o7XtkvWk5aT3pmjoesxR1A&usqp=CAU',
  },
  {
    title: 'Iron Man 3',
    subtitle: 'Iron Man 3',
    storyline: 'After an enemy has reduced Tony Stark\'s world to rubble, Iron Man must learn to trust his instincts to protect those he loves, especially his girlfriend, and fight his biggest fear: failure.',
    rating: 4.0,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6e7cnmH4EfsxAEtGxiM3-hZu-b74cfD-_jQ&usqp=CAU',
    bookmarked: false,
    genre: "fiction",
  },
  {
    id: 8,
    title: 'Demon Slayer',
    subtitle: 'Mugen Train',
    storyline: 'It\'s the Taisho period in Japan. Tanjiro, a kind-hearted boy who sells charcoal to survive, finds his family slaughtered by a demon. To make matters worse, her younger sister, Nezuko, the only survivor, was turned into a demon.',
    rating: 4.9,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjpHS2S1pH5jP4HMKAgg290LDKOLFtm3gZpw&usqp=CAU',
  },
  {    title: 'The Lion King',
    subtitle: 'The Lion King',
    storyline: 'Simba is a young lion whose destiny is to become the king of the jungle. However, a trap designed by his uncle Scar causes Mufasa, the current king, to die while trying to save the cub.',
    rating: 2.6,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwXXe0xVZD0CSHzuE1QIb6bGxmu5ZVe2F5sg&usqp=CAU',
  },
  {
    title: 'The Black Panther',
    subtitle: 'The Black Panther',
    storyline: 'Discover the story of T\'Challa, prince of the kingdom of Wakanda, who loses his father and travels to the United States, where he has contact with the Avengers. Among his skills are speed, intelligence and keen senses.',
    rating: 5.0,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSUPOKdMy5592vOb2TneQL9uMvAjFMkp5JYg&usqp=CAU',
  },
  {
    title: 'Jurassic Park 3',
    subtitle: 'Jurassic Park 3',
    storyline: 'On an island, cloned dinosaurs live in freedom and are studied in the natural environment. But an accident with the plane causes the group of seven people to be stranded on the dangerous island.',
    rating: 2.5,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3zj4OrhXSENYBTv5jeb3FBKfQwWoz9kbDYQ&usqp=CAU',
  },
  {
    title: 'Tom Clancy\'s',
    subtitle: 'Tom Clancy\'s',
    storyline: 'No Remorse tells the story of John Kelly, an elite naval officer. When a squad of Russian soldiers kills his pregnant wife in retaliation for her role in a top-secret operation, he pursues the killers at all costs.',
    rating: 2.5,
    imagePath: 'https://vitaminanerd.com.br/wp-content/uploads/2021/05/Sem-remorso-capa-vitamina-nerd.png',
  },
  {
    title: 'Godzilla vs Kong',
    subtitle: 'Godzilla vs Kong',
    storyline: 'Kong and his protectors embark on a perilous journey to find their true home. Jia, an orphan girl who has a unique and powerful bond with the mighty beast, follows the adventure. However, they soon find themselves in Godzilla\'s path, completely enraged, leaving a trail of destruction across the world.',
    rating: 3.8,
    imagePath: 'https://i1.wp.com/otageek.com.br/wp-content/uploads/2021/05/Godzilla-vs-kong.jpg?fit=1280%2C720&ssl=1',
  },
  {
    title: 'Red',
    subtitle: 'Red',
    storyline: 'During the investigation of a murder, police arrive at a photo of a suspect. But the case gets complicated when they discover that there are two men with that face.',
    rating: 3.6,
    imagePath: 'https://williammaginn.files.wordpress.com/2013/09/red-movie-poster.jpg',
  },
  {
    title: 'The Marksman',
    subtitle: 'The Marksman',
    storyline: 'The story of a farmer who lives on the Arizona border and becomes the unlikely supporter of a young Mexican who is desperately fleeing the cartel killers who pursued him to the United States.',
    rating: 1.8,
    imagePath: 'https://images-na.ssl-images-amazon.com/images/S/pv-target-images/9a47cb1b6249ba1fbbcfcef663deaf2f3717403c4213102d22836cd5b5270185._RI_V_TTW_.jpg',
  },
];

export default movies;